### ISSUE TITLE
After a client is initiated, users on iOS safari cannot scroll horizontally

### ISSUE THREAD

**Issue by longjiang** [KentoNishi/iframe-translator#5]
Demo: https://zerotohero-nuxt-g6szam6ui-zerotohero.vercel.app/en/af/all-media

A translation client is enabled in the background. iOS safari users can scroll neither the top nav bar nor the bottom nav bar, sometimes vertical scroll is also locked.

**Comment by KentoNishi** [comment]
hmm, ive only ever used this on desktop apps, so i never realized mobile had issues. i'll look into it

**Comment by KentoNishi** [comment]
i *think* i've fixed it, please try `v0.3.4` :)

**Comment by Candygoblen123** [comment]
This also seems to affect safari users on macOS

**Comment by KentoNishi** [comment]
@longjiang ping again

**Comment by KentoNishi** [comment]
@longjiang I *think* I fixed the issue in `v0.3.4`. Closing the issue due to inactivity.
